server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://openjdk-finder.us.auth0.com/
#
#
#auth0:
#  audience: ${AUTH0_API_IDENTIFIER}

app:
  cors:
    origins:
      - http://localhost:3000
